-- Insert sample patients
INSERT INTO patients (name, age, gender, phone, email, address, condition, vata_percentage, pitta_percentage, kapha_percentage, last_visit, next_appointment, status, bmi, blood_pressure, medications, dietary_restrictions, notes) VALUES
('Meera Patel', 32, 'Female', '+91 98765 43210', 'meera.patel@email.com', 'Mumbai, Maharashtra', 'PCOS', 40, 45, 35, '2024-01-15', '2024-02-15', 'active', 24.5, '120/80', ARRAY['Metformin', 'Vitamin D'], ARRAY['Gluten-free', 'Low sugar'], 'Responds well to cooling foods. Avoid spicy and oily foods.'),
('Rajesh Kumar', 45, 'Male', '+91 87654 32109', 'rajesh.kumar@email.com', 'Delhi, India', 'Diabetes Type 2', 30, 35, 45, '2024-01-10', '2024-02-10', 'follow-up', 28.2, '140/90', ARRAY['Insulin', 'Metformin', 'Lisinopril'], ARRAY['Low carb', 'No sugar'], 'Kapha constitution requires light, warm foods. Regular exercise recommended.'),
('Priya Singh', 28, 'Female', '+91 76543 21098', 'priya.singh@email.com', 'Bangalore, Karnataka', 'Digestive Issues', 50, 30, 20, '2024-01-20', '2024-02-20', 'active', 21.8, '110/70', ARRAY['Probiotics'], ARRAY['Dairy-free'], 'High Vata constitution. Needs warm, cooked foods and regular meal times.'),
('Amit Sharma', 38, 'Male', '+91 65432 10987', 'amit.sharma@email.com', 'Pune, Maharashtra', 'Hypertension', 25, 55, 20, '2024-01-05', '2024-02-05', 'inactive', 26.1, '150/95', ARRAY['Amlodipine', 'Atenolol'], ARRAY['Low sodium'], 'Pitta dominant. Avoid hot, spicy foods. Include cooling herbs and vegetables.');

-- Insert sample food items
INSERT INTO food_items (name, category, image_url, calories, protein, carbs, fat, rasa, virya, vipaka, guna, vata_compatibility, pitta_compatibility, kapha_compatibility, season, benefits, conditions) VALUES
('Basmati Rice', 'Grains', '/placeholder.svg?height=200&width=200', 130, 2.7, 28, 0.3, 'Sweet', 'Cool', 'Sweet', 'Light, Easy to digest', 'good', 'excellent', 'moderate', 'All seasons', ARRAY['Cooling', 'Easy digestion', 'Calming'], ARRAY['Pitta disorders', 'Hyperacidity', 'Inflammation']),
('Cucumber', 'Vegetables', '/placeholder.svg?height=200&width=200', 16, 0.7, 4, 0.1, 'Sweet, Astringent', 'Cool', 'Sweet', 'Light, Cooling', 'moderate', 'excellent', 'good', 'Summer', ARRAY['Hydrating', 'Cooling', 'Detoxifying'], ARRAY['Heat disorders', 'Skin issues', 'Urinary problems']),
('Bitter Gourd', 'Vegetables', '/placeholder.svg?height=200&width=200', 17, 1, 3.7, 0.2, 'Bitter', 'Cool', 'Pungent', 'Light, Dry', 'poor', 'good', 'excellent', 'Summer, Monsoon', ARRAY['Blood purifying', 'Anti-diabetic', 'Liver cleansing'], ARRAY['Diabetes', 'PCOS', 'Skin disorders']),
('Almonds', 'Nuts & Seeds', '/placeholder.svg?height=200&width=200', 579, 21, 22, 50, 'Sweet', 'Hot', 'Sweet', 'Heavy, Oily', 'excellent', 'moderate', 'poor', 'Winter', ARRAY['Brain tonic', 'Strengthening', 'Nourishing'], ARRAY['Weakness', 'Memory issues', 'Dry skin']),
('Turmeric', 'Spices', '/placeholder.svg?height=200&width=200', 354, 8, 65, 10, 'Bitter, Pungent', 'Hot', 'Pungent', 'Light, Dry', 'good', 'moderate', 'excellent', 'All seasons', ARRAY['Anti-inflammatory', 'Healing', 'Purifying'], ARRAY['Inflammation', 'Wounds', 'Respiratory issues']),
('Coconut Water', 'Beverages', '/placeholder.svg?height=200&width=200', 19, 0.7, 3.7, 0.2, 'Sweet', 'Cool', 'Sweet', 'Light, Cooling', 'good', 'excellent', 'moderate', 'Summer', ARRAY['Hydrating', 'Electrolyte balance', 'Cooling'], ARRAY['Dehydration', 'Heat stroke', 'Urinary disorders']);
